language: generic

os: osx

osx_image: xcode12.2

addons:
  homebrew:
    packages:
      - coq
    update: true

script:
  - coqc -v
  - coq_makefile -f _CoqProject -o Makefile
  - make

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10